# Generated by Django 4.1.4 on 2023-03-21 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_options_remove_contact_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
